version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  spring:
    build: 
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.backend=spring
      - traefik.frontend.rule=Host:billing.southindiantrekkers.org
      - traefik.docker.network=proxy
      - traefik.port=9091
    networks:
      - internal
      - proxy
